### ISSUE TITLE
Package should belong to JuliaCollections

### ISSUE THREAD

**Issue by o314** [BioJulia/IntervalTrees.jl#48]
Hello BioJulia,

I'm fighting with entropy in the Julia world those days. It's becoming very,
very hard to know where to grasp a recommended / authoritative package among
Julia ones, even in 2019.

Doesn't this package would be better hosted at
[JuliaCollections](http://github.com/JuliaCollections) so anyone concerned would
find it easily ?

Thanks

PS see https://github.com/BioJulia/IntervalTrees.jl/issues/32
PPS template removed since it does not apply

**Comment by BenJWard** [comment]
> Doesn't this package would be better hosted at
> JuliaCollections so anyone concerned would
> find it easily ?

IntervalTrees was made by someone in BioJulia, for biological purposes, for BioJulia, and it is maintained by people in BioJulia.

I have to mirror comments others have made in other issues you've made elsewhere in the julia ecosystem: The GitHub organisations feature is for developers, not users.

GitHub has tools to make repos discoverable (orgganizations is not one of them): allowing you to find repos by language, repository type, and by (most importantly to this issue) topic words. If you want to find a package for parsing FASTA files, limit the search to julia, and then look for the fasta keyword. Some of BioJulia repos are not tagged with keywords very well, but we are trying to make that better going forward. We would probably do well to make sure we publish software notes of our packages in the future to make them more discoverable.

**Comment by o314** [comment]
Hello JuliaBio, Ms Sabrina Ward.

*Trying to be concise, and constructive about a not so easy situation*

ABOUT JULIABIO WORKS
Sorry for the inconvenience about the overwhelming number of message if it hurts. I could remove other ones if needed. You take a long time to answer precisely and perfectly in your former comment about the situation of packages coming from JuliaBio. Thanks a lot again.

ABOUT THE GLOBAL JULIA ECOSYSTEM
Julia 1.0 has landed few month ago. Most packages did not. Still no JuliaDB 1.0. Julia is 1.1, JuliaPro always 1.0. And that's the best part. Many, many packages are frozen since 3 or more years before 1.0. And will probably not resurrect.

ABOUT THE GLOBAL FOSS PROFESSIONAL ECOSYSTEM
The threat is not the location of packages, but their number. It's not a discovery issue but an integration one and a will/agreement to build upon a few consolidated projects. A silently trend has occured some years ago, to contribute to a few consolidated project, stopping by the way the nightmare of choice among dozens of framework, most of them promised to disappear.

Key people without any more free time, difficulty to upgrade may be a premise,  Julia Computing supports approximatively 30 packages. I am deeply inclined support will be better than with Anaconda 650 python ones. And hope those practices will continue and spread in Julia landscape.

Thanks anyway to have open-source so many projects.

Best Regards

*No need to close others comments since that was my last unanswered remark.*
